### ISSUE TITLE
Restructure VM / container chapter

### ISSUE THREAD

**Issue by uekerman** [Simulation-Software-Engineering/Lecture-Material#25]
A few observations from WS21/22, where we could restructure things next year.

* Directly start VirtualBox section with practical example. Everybody has a rough idea already what a "VM" is. This is enough to show sth. Then, from the practical example motivate the theory (What exactly is a VM now? What are restrictions? ...).
* It could be nice to do 45 mins exercises directly after each 45 mins lecture:
  * VirtualBox lecture (45 mins), then VirtualBox exercise (45 mins) 
  * Vagrant lecture (45 mins), then Vagrant exercise (45 mins)
  * Docker (+ Singularity) lecture (90 mins), then Docker exercise (90 mins)
  * This now even takes 4 x 90 mins (not 3 x 90 mins), but I guess we could afford this.

**Comment by ajaust** [comment]
- Consolidate the introductory part of the sections Virtual Machines, VirtualBox, Vagrant, Containers, Docker, and Singularity. At the moment if feels like there is a lot of repetition of "Security" and what these things do in there. Things that are noteworthy and/or differ from the general statements in the introduction should still be kept in the corresponding sections.

**Comment by ajaust** [comment]
Note that "Singularity" joined the Linux Foundation and is now called [Apptainer](https://apptainer.org/).

[Link to community announcement](https://apptainer.org/news/community-announcement-20211130)

**Comment by IshaanDesai** [comment]
In https://github.com/Simulation-Software-Engineering/Lecture-Material/pull/131 and https://github.com/Simulation-Software-Engineering/Lecture-Material/pull/137 the following parts of this issue were addressed:

* Directly starting with VirtualBox and then coming to the theory of VMs.

The following points are yet to be addressed:

* Have 45 mins of one concept followed by 45 mins of exercise on the concept.
* Consolidate the introductory part of Virtual Machines, VirtualBox, Vagrant, Containers and Docker to avoid repetitions.

**Comment by MakisH** [comment]
#197 addresses all these, apart from the scheduling. We decided that the current way of doing things lets up use more time for the student presentations.

I will open a separate issue for the scheduling in case this is still a problem.
